name: Release binaries

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ['darwin', 'windows', 'linux']
        goarch: ['amd64']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1.21'
      - name: Build binary
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o release/assessment-${{ matrix.goos }}-${{ matrix.goarch }} ./cmd/assessment
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release/assessment-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_name: assessment-${{ matrix.goos }}-${{ matrix.goarch }}
          asset_content_type: application/octet-stream

